#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('WWW_PATH') or define('WWW_PATH', __DIR__);

defined('YII_DEBUG') or define('YII_DEBUG', true);


if (!defined('ENV_STATE')) {
    $env_state = get_cfg_var('switch.environment');
    define('ENV_STATE', $env_state === false ? 'dev' : $env_state);
    defined('YII_ENV') or define('YII_ENV', ENV_STATE);
}
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
